services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio_caju
    ports:
      - 5432:5432

  desafio-caju:
    build:
      context: .
    restart: on-failure:5
    environment:
      DB_NAME: desafio_caju
      DB_PORT: 5432
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - 8080:8080
    depends_on:
      - db